collectibleTypes:
  dragon-ball-card:
    title: collectdb - Dragon Ball Card
    spreadsheetId: 1peAlf56kChT4OUbtKQ2MbFpeCyELjaNqmLRWGTdd0Hw
  mtg-card:
    title: collectdb - MTG Card
    spreadsheetId: 1YC2JOMRXd7N-c8A002c1JljG4hX4JSQ5CoVlxRKNfEo
  pokemon-card:
    title: collectdb - Pokemon Card
    spreadsheetId: 1ivDMhlcRWSiy9kPMLprjWX7-uSK-0CVOGWhDgc__FJk
  sports-card:
    title: collectdb - Sports Card
    spreadsheetId: 1z0JGSjqkQwwlwfgVJCc0AI6LOFrcf5GwUj44A0eVQ88
