import 'dotenv/config';

import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { google, type sheets_v4 } from 'googleapis';
import { Document, parseDocument } from 'yaml';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';

import type { CollectibleType as CollectibleTypeMetadata, RegionDescriptor, SeriesDescriptor } from '../schema/Schema.js';
import { writeFormattedYaml } from './lib/write-formatted-yaml.js';

type SheetConfigEntry = {
    spreadsheetId?: string;
    title?: string;
};

type SheetsConfig = {
    collectibleTypes: Record<string, SheetConfigEntry>;
};

type RegionSheet = {
    title: string;
    rows: string[][];
};

type CollectibleDataset = {
    collectibleType: string;
    collectibleName: string;
    regions: RegionSheet[];
};

type CollectibleTypeMetadataMap = Record<string, CollectibleTypeMetadata>;

type RecordContext = {
    generationKey: string;
    generationName: string;
    seriesKey: string;
    seriesName: string;
};

type RecordSection = 'items' | 'products' | 'additional';

type ExportRow = {
    values: string[];
    generationKey: string;
    seriesKey: string;
    section: RecordSection;
    editionKey: string;
    groupName: string;
    recordIndex: string;
    recordKey: string;
};

const argv = await yargs(hideBin(process.argv))
    .option('config', {
        describe: 'Path to the tracked Google Sheets config file',
        type: 'string',
        default: '.sheets.yaml',
    })
    .option('readme', {
        describe: 'Path to the README file with the generated links section',
        type: 'string',
        default: 'README.md',
    })
    .option('data-root', {
        describe: 'Root data directory',
        type: 'string',
        default: 'data',
    })
    .option('collectible-type', {
        describe: 'Limit sync to one or more collectible types',
        type: 'array',
        string: true,
    })
    .option('create-missing', {
        describe: 'Create spreadsheets when a collectible type has no spreadsheetId yet',
        type: 'boolean',
        default: false,
    })
    .parse();

const README_LINKS_START = '<!-- google-sheets-links:start -->';
const README_LINKS_END = '<!-- google-sheets-links:end -->';
const skippedDirectoryNames = new Set(['test-source']);
const SHEET_AUTOGENERATED_NOTE = 'Auto-generated from the collectdb project: https://github.com/topvault/collectdb. Please submit contributions and report problems as GitHub issues or pull requests. ';

const SHEET_HEADERS = [
    'Generation',
    'Series',
    'Edition / Group',
    'Name',
    'Index',
    'Variant',
    'Release Date',
    'Description',
    'ID',
    'Key',
] as const;

function sortEntries<T>(record: Record<string, T>): [string, T][] {
    return Object.entries(record).sort(([left], [right]) => left.localeCompare(right));
}

function toRelativePath(filePath: string): string {
    return path.relative(process.cwd(), filePath).split(path.sep).join('/');
}

function titleCaseFromKey(key: string): string {
    return key
        .split('-')
        .map(part => (part.length <= 3 ? part.toUpperCase() : `${part[0].toUpperCase()}${part.slice(1)}`))
        .join(' ');
}

function stringifyCell(value: unknown): string {
    if (value === undefined || value === null) {
        return '';
    }

    if (typeof value === 'string') {
        return value;
    }

    return JSON.stringify(value);
}

function stringifyDateCell(value: unknown): string {
    if (value === undefined || value === null) {
        return '';
    }

    if (value instanceof Date) {
        return value.toISOString().slice(0, 10);
    }

    if (typeof value === 'string') {
        return value;
    }

    return JSON.stringify(value);
}

function formatCatalogLabel(name: string, key: string): string {
    return name || key;
}

function getSpreadsheetUrl(spreadsheetId: string): string {
    return `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`;
}

function normalizeSheetTitle(title: string): string {
    return title.toLowerCase();
}

function buildSheetNoteRow(): string[] {
    return [SHEET_AUTOGENERATED_NOTE, ...Array.from({ length: SHEET_HEADERS.length - 1 }, () => '')];
}

function getLongestCellLineLength(value: string): number {
    return value
        .split(/\r?\n/gu)
        .reduce((longest, line) => Math.max(longest, line.length), 0);
}

function estimateColumnPixelWidth(rows: string[][], columnIndex: number): number {
    const longestCellLength = rows.reduce((longest, row) => {
        return Math.max(longest, getLongestCellLineLength(row[columnIndex] ?? ''));
    }, 0);

    return Math.max(36, longestCellLength * 7 + 16);
}

function buildColumnWidthRequests(sheetId: number, rows: string[][]): sheets_v4.Schema$Request[] {
    return Array.from({ length: SHEET_HEADERS.length }, (_, columnIndex) => ({
        updateDimensionProperties: {
            range: {
                sheetId,
                dimension: 'COLUMNS',
                startIndex: columnIndex,
                endIndex: columnIndex + 1,
            },
            properties: {
                pixelSize: estimateColumnPixelWidth(rows, columnIndex),
            },
            fields: 'pixelSize',
        },
    }));
}

function normalizeDriveResourceId(value: string | undefined): string | undefined {
    if (!value) {
        return undefined;
    }

    const trimmed = value.trim();
    if (trimmed === '') {
        return undefined;
    }

    const folderMatch = trimmed.match(/\/folders\/([a-zA-Z0-9_-]+)/u);
    if (folderMatch) {
        return folderMatch[1];
    }

    const idMatch = trimmed.match(/[?&]id=([a-zA-Z0-9_-]+)/u);
    if (idMatch) {
        return idMatch[1];
    }

    return trimmed;
}

function formatGoogleApiError(error: unknown): string {
    if (!error || typeof error !== 'object') {
        return String(error);
    }

    const candidate = error as { message?: unknown; cause?: unknown };
    const directMessage = typeof candidate.message === 'string' ? candidate.message : undefined;

    if (candidate.cause && typeof candidate.cause === 'object') {
        const cause = candidate.cause as { message?: unknown; status?: unknown; code?: unknown };
        const causeMessage = typeof cause.message === 'string' ? cause.message : undefined;
        const causeStatus = typeof cause.status === 'string' ? cause.status : typeof cause.code === 'number' ? String(cause.code) : undefined;

        if (causeMessage && causeStatus) {
            return `${causeMessage} (${causeStatus})`;
        }

        if (causeMessage) {
            return causeMessage;
        }
    }

    return directMessage ?? String(error);
}

async function fileExists(filePath: string): Promise<boolean> {
    try {
        await stat(filePath);
        return true;
    } catch {
        return false;
    }
}

async function resolveSeriesFile(regionPath: string, generationKey: string, seriesKey: string): Promise<string> {
    const yamlPath = path.join(regionPath, `${generationKey}:${seriesKey}.yaml`);
    if (await fileExists(yamlPath)) {
        return yamlPath;
    }

    const ymlPath = path.join(regionPath, `${generationKey}:${seriesKey}.yml`);
    if (await fileExists(ymlPath)) {
        return ymlPath;
    }

    throw new Error(`Series file not found for ${generationKey}:${seriesKey} under ${toRelativePath(regionPath)}.`);
}

async function resolveCollectibleTypeFile(collectiblePath: string): Promise<string> {
    const yamlPath = path.join(collectiblePath, '_type.yaml');
    if (await fileExists(yamlPath)) {
        return yamlPath;
    }

    const ymlPath = path.join(collectiblePath, '_type.yml');
    if (await fileExists(ymlPath)) {
        return ymlPath;
    }

    throw new Error(`Collectible type metadata file not found under ${toRelativePath(collectiblePath)}.`);
}

async function resolveRegionDescriptorFile(regionPath: string): Promise<string> {
    const yamlPath = path.join(regionPath, '_region.yaml');
    if (await fileExists(yamlPath)) {
        return yamlPath;
    }

    const ymlPath = path.join(regionPath, '_region.yml');
    if (await fileExists(ymlPath)) {
        return ymlPath;
    }

    throw new Error(`Region metadata file not found under ${toRelativePath(regionPath)}.`);
}

async function parseYamlFile<T>(filePath: string): Promise<T> {
    const source = await readFile(filePath, 'utf8');
    const document = parseDocument(source, {
        prettyErrors: false,
        strict: true,
        uniqueKeys: true,
    });

    if (document.errors.length > 0) {
        throw new Error(`${toRelativePath(filePath)}: ${document.errors.map(error => error.message).join('; ')}`);
    }

    return document.toJS() as T;
}

function getEditionMetadata(series: SeriesDescriptor, editionKey: string): { editionName: string; releaseDate: string } {
    if (!series.editions || !(editionKey in series.editions)) {
        return {
            editionName: editionKey === 'unlimited' ? 'Unlimited' : editionKey,
            releaseDate: '',
        };
    }

    const edition = series.editions[editionKey];
    if (typeof edition === 'string') {
        return {
            editionName: edition,
            releaseDate: '',
        };
    }

    return {
        editionName: edition.name,
        releaseDate: stringifyDateCell(edition.releaseDate),
    };
}

function resolveReleaseDate(itemReleaseDate: unknown, seriesReleaseDate: unknown): string {
    return stringifyDateCell(itemReleaseDate) || stringifyDateCell(seriesReleaseDate);
}

function compareOptionalDates(left: string, right: string): number {
    if (left === right) {
        return 0;
    }

    if (left === '') {
        return 1;
    }

    if (right === '') {
        return -1;
    }

    const leftTimestamp = Date.parse(left);
    const rightTimestamp = Date.parse(right);
    const leftIsDate = !Number.isNaN(leftTimestamp);
    const rightIsDate = !Number.isNaN(rightTimestamp);

    if (leftIsDate && rightIsDate && leftTimestamp !== rightTimestamp) {
        return leftTimestamp - rightTimestamp;
    }

    if (leftIsDate !== rightIsDate) {
        return leftIsDate ? -1 : 1;
    }

    return left.localeCompare(right);
}

function pickEarlierDate(current: string, candidate: string): string {
    if (current === '') {
        return candidate;
    }

    if (candidate === '') {
        return current;
    }

    return compareOptionalDates(current, candidate) <= 0 ? current : candidate;
}

function compareEditionKeys(left: string, right: string): number {
    if (left === right) {
        return 0;
    }

    const prioritizedEditionOrder = new Map<string, number>([
        ['1st-edition', 0],
        ['shadowless', 1],
        ['unlimited', 2],
    ]);
    const leftPriority = prioritizedEditionOrder.get(left);
    const rightPriority = prioritizedEditionOrder.get(right);

    if (leftPriority !== undefined || rightPriority !== undefined) {
        if (leftPriority === undefined) {
            return 1;
        }

        if (rightPriority === undefined) {
            return -1;
        }

        return leftPriority - rightPriority;
    }

    if (left === 'unlimited') {
        return -1;
    }

    if (right === 'unlimited') {
        return 1;
    }

    if (left === '') {
        return 1;
    }

    if (right === '') {
        return -1;
    }

    return left.localeCompare(right);
}

function compareIndexes(left: string, right: string): number {
    if (left === right) {
        return 0;
    }

    if (left === '') {
        return 1;
    }

    if (right === '') {
        return -1;
    }

    const leftMatch = left.match(/^(\d+)([a-zA-Z]?)$/u);
    const rightMatch = right.match(/^(\d+)([a-zA-Z]?)$/u);

    if (leftMatch && rightMatch) {
        const leftNumber = Number.parseInt(leftMatch[1], 10);
        const rightNumber = Number.parseInt(rightMatch[1], 10);

        if (leftNumber !== rightNumber) {
            return leftNumber - rightNumber;
        }

        return leftMatch[2].localeCompare(rightMatch[2]);
    }

    return left.localeCompare(right);
}

function sortExportRows(rows: ExportRow[], seriesReleaseDates: Map<string, string>, generationReleaseDates: Map<string, string>): string[][] {
    return rows
        .sort((left, right) => {
            const leftGenerationReleaseDate = generationReleaseDates.get(left.generationKey) ?? '';
            const rightGenerationReleaseDate = generationReleaseDates.get(right.generationKey) ?? '';
            const generationDateComparison = compareOptionalDates(leftGenerationReleaseDate, rightGenerationReleaseDate);
            if (generationDateComparison !== 0) {
                return generationDateComparison;
            }

            const generationComparison = left.generationKey.localeCompare(right.generationKey);
            if (generationComparison !== 0) {
                return generationComparison;
            }

            const leftSeriesReleaseDate = seriesReleaseDates.get(`${left.generationKey}:${left.seriesKey}`) ?? '';
            const rightSeriesReleaseDate = seriesReleaseDates.get(`${right.generationKey}:${right.seriesKey}`) ?? '';
            const seriesDateComparison = compareOptionalDates(leftSeriesReleaseDate, rightSeriesReleaseDate);
            if (seriesDateComparison !== 0) {
                return seriesDateComparison;
            }

            const seriesComparison = left.seriesKey.localeCompare(right.seriesKey);
            if (seriesComparison !== 0) {
                return seriesComparison;
            }

            const leftSectionOrder = left.section === 'additional' ? 1 : 0;
            const rightSectionOrder = right.section === 'additional' ? 1 : 0;
            if (leftSectionOrder !== rightSectionOrder) {
                return leftSectionOrder - rightSectionOrder;
            }

            if (left.section !== 'additional' && right.section !== 'additional') {
                const editionComparison = compareEditionKeys(left.editionKey, right.editionKey);
                if (editionComparison !== 0) {
                    return editionComparison;
                }
            }

            const groupComparison = left.groupName.localeCompare(right.groupName);
            if (groupComparison !== 0) {
                return groupComparison;
            }

            const indexComparison = compareIndexes(left.recordIndex, right.recordIndex);
            if (indexComparison !== 0) {
                return indexComparison;
            }

            return left.recordKey.localeCompare(right.recordKey);
        })
        .map(row => row.values);
}

function buildRecordKey(
    context: RecordContext,
    section: RecordSection,
    itemKey: string,
    groupKey = '',
    variantKey = '',
    editionKey = ''
): string {
    const pathSegments = [`${context.generationKey}:${context.seriesKey}`];

    if (section === 'additional') {
        pathSegments.push('additional', groupKey, 'items', itemKey);
    } else {
        pathSegments.push(section, itemKey);
    }

    if (editionKey !== '') {
        pathSegments.push('editions', editionKey);
    }

    if (variantKey !== '') {
        pathSegments.push('variants', variantKey);
    }

    return pathSegments.join('/');
}

function normalizeIndexValue(value: unknown): string {
    if (typeof value === 'number') {
        return String(value);
    }

    if (typeof value === 'string') {
        return value;
    }

    return '';
}

function getRecordIndex(record: Record<string, unknown>): string {
    const normalized = normalizeIndexValue(record.index);
    if (normalized === '') {
        return '';
    }

    return normalized;
}

function getStringProperty(record: Record<string, unknown>, propertyName: string): string {
    const value = record[propertyName];
    return typeof value === 'string' ? value : '';
}

function getInlineVariant(record: Record<string, unknown>): { variantName: string; variantDescription: string } {
    const variantValue = record.variant;
    if (!variantValue || typeof variantValue !== 'object' || Array.isArray(variantValue)) {
        return {
            variantName: '',
            variantDescription: '',
        };
    }

    return {
        variantName: stringifyCell((variantValue as { name?: unknown }).name),
        variantDescription: getStringProperty(variantValue as Record<string, unknown>, 'description'),
    };
}

function normalizeDescription(value: string): string {
    return value.replace(/\s*[\r\n]+\s*/gu, ' ').trim();
}

function resolveDescription(itemDescription: string, variantDescription = '', groupDescription = ''): string {
    return normalizeDescription(variantDescription || itemDescription || groupDescription);
}

function buildRow(
    context: RecordContext,
    section: RecordSection,
    editionKey: string,
    editionName: string,
    name: string,
    groupKey: string,
    groupName: string,
    recordIndex: string,
    variantName: string,
    id: string,
    recordKey: string,
    releaseDate: string,
    description: string
): ExportRow {
    const editionOrGroupLabel = formatCatalogLabel(editionName, editionKey) || formatCatalogLabel(groupName, groupKey);

    return {
        generationKey: context.generationKey,
        seriesKey: context.seriesKey,
        section,
        editionKey,
        groupName: formatCatalogLabel(groupName, groupKey),
        recordIndex,
        recordKey,
        values: [
            formatCatalogLabel(context.generationName, context.generationKey),
            formatCatalogLabel(context.seriesName, context.seriesKey),
            editionOrGroupLabel,
            name,
            recordIndex,
            variantName,
            releaseDate,
            description,
            id,
            recordKey,
        ],
    };
}

function collectVariantRows(
    rows: ExportRow[],
    context: RecordContext,
    section: RecordSection,
    series: SeriesDescriptor,
    groupKey: string,
    groupName: string,
    groupDescription: string,
    itemKey: string,
    itemData: Record<string, unknown>
): void {
    if (!itemData.variants || typeof itemData.variants !== 'object' || Array.isArray(itemData.variants)) {
        return;
    }

    const recordIndex = getRecordIndex(itemData);
    const itemName = stringifyCell(itemData.name);
    const itemDescription = getStringProperty(itemData, 'description');
    const releaseDate = resolveReleaseDate(itemData.releaseDate, series.releaseDate);

    for (const [variantKey, variantValue] of sortEntries(itemData.variants as Record<string, Record<string, unknown>>)) {
        const explicitEditionKey = typeof variantValue.edition === 'string' ? variantValue.edition : '';
        const effectiveEditionKey = explicitEditionKey || 'unlimited';
        const editionMetadata = getEditionMetadata(series, effectiveEditionKey);
        const variantName = stringifyCell(variantValue.name);
        const variantDescription = getStringProperty(variantValue, 'description');
        rows.push(
            buildRow(
                context,
                section,
                effectiveEditionKey,
                editionMetadata.editionName,
                itemName,
                groupKey,
                groupName,
                recordIndex,
                variantName,
                stringifyCell(variantValue.id),
                buildRecordKey(context, section, itemKey, groupKey, variantKey, effectiveEditionKey),
                releaseDate,
                resolveDescription(itemDescription, variantDescription, groupDescription)
            )
        );
    }
}

function collectDiscreteEntryRows(
    rows: ExportRow[],
    context: RecordContext,
    section: RecordSection,
    itemKey: string,
    itemData: Record<string, unknown>,
    series: SeriesDescriptor,
    groupKey = '',
    groupName = '',
    groupDescription = ''
): void {
    const editions = itemData.editions as Record<string, string>;
    const recordIndex = getRecordIndex(itemData);
    const itemName = stringifyCell(itemData.name);
    const itemDescription = getStringProperty(itemData, 'description');
    const inlineVariant = getInlineVariant(itemData);
    const releaseDate = resolveReleaseDate(itemData.releaseDate, series.releaseDate);

    for (const [editionKey, editionId] of sortEntries(editions)) {
        const editionMetadata = getEditionMetadata(series, editionKey);
        rows.push(
            buildRow(
                context,
                section,
                editionKey,
                editionMetadata.editionName,
                itemName,
                groupKey,
                groupName,
                recordIndex,
                inlineVariant.variantName,
                editionId,
                buildRecordKey(context, section, itemKey, groupKey, '', editionKey),
                releaseDate,
                resolveDescription(itemDescription, inlineVariant.variantDescription, groupDescription)
            )
        );
    }

    collectVariantRows(rows, context, section, series, groupKey, groupName, groupDescription, itemKey, itemData);
}

function collectSectionRows(
    rows: ExportRow[],
    context: RecordContext,
    section: 'items' | 'products',
    entries: Record<string, unknown>,
    series: SeriesDescriptor
): void {
    for (const [itemKey, itemValue] of sortEntries(entries)) {
        if (!itemValue || typeof itemValue !== 'object' || Array.isArray(itemValue) || 'referenceOf' in itemValue) {
            continue;
        }

        collectDiscreteEntryRows(rows, context, section, itemKey, itemValue as Record<string, unknown>, series);
    }
}

function collectAdditionalRows(
    rows: ExportRow[],
    context: RecordContext,
    series: SeriesDescriptor,
    additional: NonNullable<SeriesDescriptor['additional']>
): void {
    for (const [groupKey, groupValue] of sortEntries(additional)) {
        for (const [itemKey, itemValue] of sortEntries(groupValue.items)) {
            if (!itemValue || typeof itemValue !== 'object' || Array.isArray(itemValue) || 'referenceOf' in itemValue) {
                continue;
            }

            const itemRecord = itemValue as Record<string, unknown>;
            const recordIndex = getRecordIndex(itemValue as Record<string, unknown>);
            const itemName = stringifyCell((itemValue as { name?: string }).name);
            const itemDescription = getStringProperty(itemRecord, 'description');
            const inlineVariant = getInlineVariant(itemRecord);
            const groupDescription = stringifyCell(groupValue.description);
            const releaseDate = resolveReleaseDate((itemValue as { releaseDate?: string }).releaseDate, series.releaseDate);

            rows.push(
                buildRow(
                    context,
                    'additional',
                    '',
                    '',
                    itemName,
                    groupKey,
                    groupValue.name,
                    recordIndex,
                    inlineVariant.variantName,
                    stringifyCell((itemValue as { id?: string }).id),
                    buildRecordKey(context, 'additional', itemKey, groupKey),
                    releaseDate,
                    resolveDescription(itemDescription, inlineVariant.variantDescription, groupDescription)
                )
            );

            collectVariantRows(
                rows,
                context,
                'additional',
                series,
                groupKey,
                groupValue.name,
                groupDescription,
                itemKey,
                itemValue as Record<string, unknown>
            );
        }
    }
}

async function buildRegionSheets(regionPath: string, region: RegionDescriptor): Promise<RegionSheet[]> {
    const itemRows: ExportRow[] = [];
    const productRows: ExportRow[] = [];
    const seriesReleaseDates = new Map<string, string>();
    const generationReleaseDates = new Map<string, string>();

    for (const [generationKey, generationValue] of sortEntries(region.generations ?? {})) {
        for (const seriesKey of generationValue.series ?? []) {
            const seriesFilePath = await resolveSeriesFile(regionPath, generationKey, seriesKey);
            const seriesData = await parseYamlFile<SeriesDescriptor>(seriesFilePath);
            const seriesReleaseDate = stringifyDateCell(seriesData.releaseDate);
            const seriesMapKey = `${generationKey}:${seriesKey}`;
            seriesReleaseDates.set(seriesMapKey, seriesReleaseDate);
            generationReleaseDates.set(generationKey, pickEarlierDate(generationReleaseDates.get(generationKey) ?? '', seriesReleaseDate));
            const context: RecordContext = {
                generationKey,
                generationName: generationValue.name,
                seriesKey,
                seriesName: seriesData.name,
            };

            collectSectionRows(itemRows, context, 'items', seriesData.items, seriesData);

            if (seriesData.products) {
                collectSectionRows(productRows, context, 'products', seriesData.products, seriesData);
            }

            if (seriesData.additional) {
                collectAdditionalRows(itemRows, context, seriesData, seriesData.additional);
            }
        }
    }

    const regionSheets: RegionSheet[] = [
        {
            title: region.name,
            rows: [Array.from(SHEET_HEADERS), ...sortExportRows(itemRows, seriesReleaseDates, generationReleaseDates)],
        },
    ];

    if (productRows.length > 0) {
        regionSheets.push({
            title: `${region.name} (products)`,
            rows: [Array.from(SHEET_HEADERS), ...sortExportRows(productRows, seriesReleaseDates, generationReleaseDates)],
        });
    }

    return regionSheets;
}

async function getCollectibleTypes(dataRoot: string): Promise<string[]> {
    const entries = await readdir(dataRoot, { withFileTypes: true });

    return entries
        .filter(entry => entry.isDirectory() && !entry.name.startsWith('.') && !skippedDirectoryNames.has(entry.name))
        .map(entry => entry.name)
        .sort((left, right) => left.localeCompare(right));
}

async function loadCollectibleTypesMetadata(dataRoot: string, collectibleTypes: string[]): Promise<CollectibleTypeMetadataMap> {
    const metadata: CollectibleTypeMetadataMap = {};

    for (const collectibleType of collectibleTypes) {
        const collectiblePath = path.join(dataRoot, collectibleType);
        const metadataPath = await resolveCollectibleTypeFile(collectiblePath);
        metadata[collectibleType] = await parseYamlFile<CollectibleTypeMetadata>(metadataPath);
    }

    return metadata;
}

async function buildDatasets(
    dataRoot: string,
    collectibleTypes: string[],
    collectibleTypeMetadata: CollectibleTypeMetadataMap
): Promise<CollectibleDataset[]> {
    const datasets: CollectibleDataset[] = [];

    for (const collectibleType of collectibleTypes) {
        const collectiblePath = path.join(dataRoot, collectibleType);
        const metadata = collectibleTypeMetadata[collectibleType];
        if (!metadata) {
            throw new Error(`Missing collectible type metadata for ${collectibleType}.`);
        }

        const regionEntries = await readdir(collectiblePath, { withFileTypes: true });
        const regions: RegionSheet[] = [];

        for (const entry of regionEntries) {
            if (!entry.isDirectory() || entry.name.startsWith('.')) {
                continue;
            }

            const regionPath = path.join(collectiblePath, entry.name);
            const hasRegionDescriptor = (await fileExists(path.join(regionPath, '_region.yaml'))) || (await fileExists(path.join(regionPath, '_region.yml')));
            if (!hasRegionDescriptor) {
                continue;
            }

            const regionDescriptorPath = await resolveRegionDescriptorFile(regionPath);
            const regionDescriptor = await parseYamlFile<RegionDescriptor>(regionDescriptorPath);
            regions.push(...(await buildRegionSheets(regionPath, regionDescriptor)));
        }

        datasets.push({
            collectibleType,
            collectibleName: metadata.name,
            regions: regions.sort((left, right) => left.title.localeCompare(right.title)),
        });
    }

    return datasets;
}

async function loadConfig(configPath: string): Promise<SheetsConfig> {
    const source = await readFile(configPath, 'utf8');
    const document = parseDocument(source, {
        prettyErrors: false,
        strict: true,
        uniqueKeys: true,
    });

    if (document.errors.length > 0) {
        throw new Error(`${toRelativePath(configPath)}: ${document.errors.map(error => error.message).join('; ')}`);
    }

    const parsed = document.toJS() as Partial<SheetsConfig>;

    return {
        collectibleTypes: parsed.collectibleTypes ?? {},
    };
}

function normalizeConfig(config: SheetsConfig): SheetsConfig {
    return {
        collectibleTypes: Object.fromEntries(
            sortEntries(config.collectibleTypes).map(([collectibleType, entry]) => [
                collectibleType,
                {
                    ...(entry.title ? { title: entry.title } : {}),
                    ...(entry.spreadsheetId ? { spreadsheetId: entry.spreadsheetId } : {}),
                },
            ])
        ),
    };
}

async function saveConfig(configPath: string, config: SheetsConfig): Promise<void> {
    const yamlDocument = new Document(normalizeConfig(config));
    await writeFormattedYaml(configPath, yamlDocument);
}

function getDefaultSheetTitle(collectibleName: string): string {
    return `collectdb: ${collectibleName}`;
}

function ensureConfigEntries(config: SheetsConfig, collectibleTypes: string[], collectibleTypeMetadata: CollectibleTypeMetadataMap): void {
    for (const collectibleType of collectibleTypes) {
        const collectibleName = collectibleTypeMetadata[collectibleType]?.name ?? titleCaseFromKey(collectibleType);
        const nextTitle = getDefaultSheetTitle(collectibleName);
        const previousDefaultTitles = new Set([collectibleName, `collectdb - ${collectibleName}`]);

        config.collectibleTypes[collectibleType] ??= {
            title: nextTitle,
        };

        if (
            !config.collectibleTypes[collectibleType].title ||
            previousDefaultTitles.has(config.collectibleTypes[collectibleType].title ?? '')
        ) {
            config.collectibleTypes[collectibleType].title = nextTitle;
        }
    }
}

async function updateReadme(readmePath: string, config: SheetsConfig, collectibleTypeMetadata: CollectibleTypeMetadataMap): Promise<void> {
    const source = await readFile(readmePath, 'utf8');
    const startIndex = source.indexOf(README_LINKS_START);
    const endIndex = source.indexOf(README_LINKS_END);

    if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
        throw new Error(`README markers ${README_LINKS_START} and ${README_LINKS_END} were not found in ${toRelativePath(readmePath)}.`);
    }

    const lines = sortEntries(config.collectibleTypes).flatMap(([collectibleType, entry]) => {
        const metadata = collectibleTypeMetadata[collectibleType];
        if (metadata?.support === 'none') {
            return [];
        }

        const label = metadata?.name ?? titleCaseFromKey(collectibleType);
        if (!entry.spreadsheetId) {
            return [`- ${label}: pending initial sheet bootstrap`];
        }

        return [`- [${label}](${getSpreadsheetUrl(entry.spreadsheetId)})`];
    });

    const replacement = `${README_LINKS_START}\n${lines.join('\n')}\n${README_LINKS_END}`;
    const nextSource = `${source.slice(0, startIndex)}${replacement}${source.slice(endIndex + README_LINKS_END.length)}`;

    if (nextSource !== source) {
        await writeFile(readmePath, nextSource, 'utf8');
    }
}

function loadCredentials(): { client_email: string; private_key: string; project_id?: string } {
    const json = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;
    if (!json) {
        throw new Error('Missing Google service account credentials. Set GOOGLE_SERVICE_ACCOUNT_JSON.');
    }

    const credentials = JSON.parse(json) as { client_email: string; private_key: string; project_id?: string };

    return {
        ...credentials,
        private_key: credentials.private_key.replace(/\\n/g, '\n'),
    };
}

async function buildGoogleClients() {
    const credentials = loadCredentials();
    const auth = new google.auth.GoogleAuth({
        credentials,
        scopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive'],
    });

    return {
        drive: google.drive({ version: 'v3', auth }),
        sheets: google.sheets({ version: 'v4', auth }),
    };
}

async function preflightCheckDriveAccess(
    driveApi: ReturnType<typeof google.drive>,
    parentFolderId: string | undefined,
    sharedDriveId: string | undefined
): Promise<void> {
    if (sharedDriveId) {
        try {
            const response = await driveApi.drives.get({
                driveId: sharedDriveId,
                fields: 'id,name',
            });

            console.log(`Verified shared drive access: ${response.data.name ?? sharedDriveId}`);
        } catch (error) {
            throw new Error(
                `Configured shared drive ${sharedDriveId} is not accessible to the service account. ${formatGoogleApiError(error)}`
            );
        }
    }

    if (!parentFolderId) {
        return;
    }

    try {
        const response = await driveApi.files.get({
            fileId: parentFolderId,
            fields: 'id,name,mimeType,driveId',
            supportsAllDrives: true,
        });

        if (response.data.mimeType !== 'application/vnd.google-apps.folder') {
            throw new Error(`Configured parent ${parentFolderId} is not a Drive folder.`);
        }

        if (sharedDriveId && response.data.driveId && response.data.driveId !== sharedDriveId) {
            throw new Error(
                `Configured parent folder ${parentFolderId} belongs to shared drive ${response.data.driveId}, not ${sharedDriveId}.`
            );
        }

        console.log(`Verified parent folder access: ${response.data.name ?? parentFolderId}`);
    } catch (error) {
        if (error instanceof Error && error.message.startsWith('Configured parent')) {
            throw error;
        }

        throw new Error(
            `Configured parent folder ${parentFolderId} is not accessible to the service account. ${formatGoogleApiError(error)}`
        );
    }
}

async function createSpreadsheet(
    driveApi: ReturnType<typeof google.drive>,
    sheetsApi: ReturnType<typeof google.sheets>,
    collectibleType: string,
    title: string,
    regions: RegionSheet[],
    parentFolderId: string | undefined
): Promise<string> {
    if (parentFolderId) {
        const response = await driveApi.files.create({
            requestBody: {
                name: title,
                mimeType: 'application/vnd.google-apps.spreadsheet',
                parents: [parentFolderId],
            },
            fields: 'id',
            supportsAllDrives: true,
        });

        const spreadsheetId = response.data.id;
        if (!spreadsheetId) {
            throw new Error(`Google Drive did not return a spreadsheet ID for ${collectibleType}.`);
        }

        if (regions.length > 0) {
            const metadata = await sheetsApi.spreadsheets.get({
                spreadsheetId,
                fields: 'sheets.properties(sheetId,title)',
            });

            const firstSheetId = metadata.data.sheets?.[0]?.properties?.sheetId;
            if (firstSheetId !== undefined && firstSheetId !== null) {
                const [firstRegion, ...remainingRegions] = regions;
                const requests = [
                    {
                        updateSheetProperties: {
                            properties: {
                                sheetId: firstSheetId,
                                title: firstRegion.title,
                            },
                            fields: 'title',
                        },
                    },
                    ...remainingRegions.map(region => ({
                        addSheet: {
                            properties: {
                                title: region.title,
                            },
                        },
                    })),
                ];

                await sheetsApi.spreadsheets.batchUpdate({
                    spreadsheetId,
                    requestBody: { requests },
                });
            }
        }

        return spreadsheetId;
    }

    const response = await sheetsApi.spreadsheets.create({
        requestBody: {
            properties: { title },
            sheets: regions.map((region, index) => ({
                properties: {
                    title: region.title,
                    index,
                },
            })),
        },
        fields: 'spreadsheetId',
    });

    const spreadsheetId = response.data.spreadsheetId;
    if (!spreadsheetId) {
        throw new Error(`Google Sheets did not return a spreadsheetId for ${collectibleType}.`);
    }

    return spreadsheetId;
}

async function maybeAttachToFolder(
    driveApi: ReturnType<typeof google.drive>,
    spreadsheetId: string,
    parentFolderId: string | undefined
): Promise<void> {
    if (!parentFolderId) {
        return;
    }

    const metadata = await driveApi.files.get({
        fileId: spreadsheetId,
        fields: 'parents',
        supportsAllDrives: true,
    });

    await driveApi.files.update({
        fileId: spreadsheetId,
        addParents: parentFolderId,
        removeParents: metadata.data.parents?.join(','),
        fields: 'id, parents',
        supportsAllDrives: true,
    });
}

async function ensurePublicReaderPermission(driveApi: ReturnType<typeof google.drive>, spreadsheetId: string): Promise<void> {
    const permissions = await driveApi.permissions.list({
        fileId: spreadsheetId,
        fields: 'permissions(id,type,role)',
        supportsAllDrives: true,
    });

    const alreadyShared = permissions.data.permissions?.some(
        (permission: { type?: string | null; role?: string | null }) => permission.type === 'anyone' && permission.role === 'reader'
    );
    if (alreadyShared) {
        return;
    }

    await driveApi.permissions.create({
        fileId: spreadsheetId,
        requestBody: {
            type: 'anyone',
            role: 'reader',
        },
        fields: 'id',
        supportsAllDrives: true,
    });
}

async function ensureSpreadsheetTitle(
    sheetsApi: ReturnType<typeof google.sheets>,
    spreadsheetId: string,
    title: string
): Promise<void> {
    const metadata = await sheetsApi.spreadsheets.get({
        spreadsheetId,
        fields: 'properties.title',
    });

    if (metadata.data.properties?.title === title) {
        return;
    }

    await sheetsApi.spreadsheets.batchUpdate({
        spreadsheetId,
        requestBody: {
            requests: [
                {
                    updateSpreadsheetProperties: {
                        properties: { title },
                        fields: 'title',
                    },
                },
            ],
        },
    });
}

async function ensureRegionTabs(
    sheetsApi: ReturnType<typeof google.sheets>,
    spreadsheetId: string,
    regions: RegionSheet[]
): Promise<Map<string, number>> {
    const metadata = await sheetsApi.spreadsheets.get({
        spreadsheetId,
        fields: 'sheets.properties(sheetId,title)',
    });

    const titleToSheetId = new Map<string, number>();
    const normalizedTitleToSheet = new Map<string, { sheetId: number; title: string }>();
    for (const sheet of metadata.data.sheets ?? []) {
        if (!sheet.properties?.title || sheet.properties.sheetId === undefined || sheet.properties.sheetId === null) {
            continue;
        }

        titleToSheetId.set(sheet.properties.title, sheet.properties.sheetId);
        normalizedTitleToSheet.set(normalizeSheetTitle(sheet.properties.title), {
            sheetId: sheet.properties.sheetId,
            title: sheet.properties.title,
        });
    }

    const requests: sheets_v4.Schema$Request[] = [];

    for (const region of regions) {
        if (titleToSheetId.has(region.title)) {
            continue;
        }

        const matchingSheet = normalizedTitleToSheet.get(normalizeSheetTitle(region.title));
        if (matchingSheet) {
            titleToSheetId.delete(matchingSheet.title);
            titleToSheetId.set(region.title, matchingSheet.sheetId);
            normalizedTitleToSheet.set(normalizeSheetTitle(region.title), {
                sheetId: matchingSheet.sheetId,
                title: region.title,
            });

            requests.push({
                updateSheetProperties: {
                    properties: {
                        sheetId: matchingSheet.sheetId,
                        title: region.title,
                    },
                    fields: 'title',
                },
            });

            continue;
        }

        requests.push({
            addSheet: {
                properties: {
                    title: region.title,
                },
            },
        });
    }

    if (requests.length > 0) {
        await sheetsApi.spreadsheets.batchUpdate({
            spreadsheetId,
            requestBody: { requests },
        });
    }

    const refreshed = await sheetsApi.spreadsheets.get({
        spreadsheetId,
        fields: 'sheets.properties(sheetId,title)',
    });

    const refreshedMap = new Map<string, number>();
    for (const sheet of refreshed.data.sheets ?? []) {
        if (!sheet.properties?.title || sheet.properties.sheetId === undefined || sheet.properties.sheetId === null) {
            continue;
        }

        refreshedMap.set(sheet.properties.title, sheet.properties.sheetId);
    }

    return refreshedMap;
}

async function syncSheetValues(
    sheetsApi: ReturnType<typeof google.sheets>,
    spreadsheetId: string,
    regions: RegionSheet[],
    sheetIds: Map<string, number>
): Promise<void> {
    for (const region of regions) {
        const values = [buildSheetNoteRow(), ...region.rows];

        await sheetsApi.spreadsheets.values.clear({
            spreadsheetId,
            range: `${region.title}!A:Z`,
        });

        await sheetsApi.spreadsheets.values.update({
            spreadsheetId,
            range: `${region.title}!A1`,
            valueInputOption: 'RAW',
            requestBody: {
                values,
            },
        });
    }

    const requests = regions.flatMap(region => {
        const sheetId = sheetIds.get(region.title);
        if (sheetId === undefined) {
            return [];
        }

        const columnWidthRequests = buildColumnWidthRequests(sheetId, region.rows);

        return [
            {
                updateSheetProperties: {
                    properties: {
                        sheetId,
                        gridProperties: {
                            frozenRowCount: 2,
                        },
                    },
                    fields: 'gridProperties.frozenRowCount',
                },
            },
            {
                unmergeCells: {
                    range: {
                        sheetId,
                        startRowIndex: 0,
                        endRowIndex: 1,
                        startColumnIndex: 0,
                        endColumnIndex: SHEET_HEADERS.length,
                    },
                },
            },
            {
                mergeCells: {
                    range: {
                        sheetId,
                        startRowIndex: 0,
                        endRowIndex: 1,
                        startColumnIndex: 0,
                        endColumnIndex: SHEET_HEADERS.length,
                    },
                    mergeType: 'MERGE_ALL',
                },
            },
            {
                repeatCell: {
                    range: {
                        sheetId,
                        startRowIndex: 0,
                        endRowIndex: 1,
                        startColumnIndex: 0,
                        endColumnIndex: SHEET_HEADERS.length,
                    },
                    cell: {
                        userEnteredFormat: {
                            backgroundColorStyle: {
                                rgbColor: {
                                    red: 0.95,
                                    green: 0.97,
                                    blue: 1,
                                },
                            },
                            textFormat: {
                                italic: true,
                            },
                            wrapStrategy: 'WRAP',
                        },
                    },
                    fields: 'userEnteredFormat.backgroundColorStyle,userEnteredFormat.textFormat.italic,userEnteredFormat.wrapStrategy',
                },
            },
            {
                repeatCell: {
                    range: {
                        sheetId,
                        startRowIndex: 1,
                        endRowIndex: 2,
                        startColumnIndex: 0,
                        endColumnIndex: SHEET_HEADERS.length,
                    },
                    cell: {
                        userEnteredFormat: {
                            textFormat: {
                                bold: true,
                            },
                        },
                    },
                    fields: 'userEnteredFormat.textFormat.bold',
                },
            },
            {
                setBasicFilter: {
                    filter: {
                        range: {
                            sheetId,
                            startRowIndex: 1,
                            startColumnIndex: 0,
                            endColumnIndex: SHEET_HEADERS.length,
                        },
                    },
                },
            },
            ...columnWidthRequests,
        ];
    });

    if (requests.length > 0) {
        await sheetsApi.spreadsheets.batchUpdate({
            spreadsheetId,
            requestBody: { requests },
        });
    }
}

async function main(): Promise<void> {
    const configPath = path.resolve(process.cwd(), argv.config);
    const readmePath = path.resolve(process.cwd(), argv.readme);
    const dataRoot = path.resolve(process.cwd(), argv['data-root']);
    const filter = argv['collectible-type'] ? new Set(argv['collectible-type']) : null;

    const { drive, sheets } = await buildGoogleClients();
    const parentFolderId = normalizeDriveResourceId(process.env.GOOGLE_SHEETS_PARENT_FOLDER_ID);
    const sharedDriveId = normalizeDriveResourceId(process.env.GOOGLE_SHARED_DRIVE_ID);

    await preflightCheckDriveAccess(drive, parentFolderId, sharedDriveId);

    const allCollectibleTypes = await getCollectibleTypes(dataRoot);
    const collectibleTypeMetadata = await loadCollectibleTypesMetadata(dataRoot, allCollectibleTypes);
    const targetCollectibleTypes = filter ? allCollectibleTypes.filter(collectibleType => filter.has(collectibleType)) : allCollectibleTypes;
    const datasets = await buildDatasets(dataRoot, targetCollectibleTypes, collectibleTypeMetadata);
    const config = await loadConfig(configPath);
    ensureConfigEntries(config, allCollectibleTypes, collectibleTypeMetadata);

    for (const dataset of datasets) {
        const configEntry = config.collectibleTypes[dataset.collectibleType];
        if (!configEntry) {
            throw new Error(`Missing Google Sheets config entry for ${dataset.collectibleType}.`);
        }

        if (!configEntry.spreadsheetId) {
            if (!argv['create-missing']) {
                throw new Error(`Missing spreadsheetId for ${dataset.collectibleType}. Re-run with --create-missing to bootstrap it.`);
            }

            configEntry.spreadsheetId = await createSpreadsheet(
                drive,
                sheets,
                dataset.collectibleType,
                configEntry.title ?? getDefaultSheetTitle(dataset.collectibleName),
                dataset.regions,
                parentFolderId
            );
        }

        await ensurePublicReaderPermission(drive, configEntry.spreadsheetId);
        await ensureSpreadsheetTitle(sheets, configEntry.spreadsheetId, configEntry.title ?? getDefaultSheetTitle(dataset.collectibleName));
        const sheetIds = await ensureRegionTabs(sheets, configEntry.spreadsheetId, dataset.regions);
        await syncSheetValues(sheets, configEntry.spreadsheetId, dataset.regions, sheetIds);
        console.log(`Synced ${dataset.collectibleType} -> ${getSpreadsheetUrl(configEntry.spreadsheetId)}`);
    }

    await saveConfig(configPath, config);
    await updateReadme(readmePath, config, collectibleTypeMetadata);
}

await main();